"""Order-n Markov surrogates over units and over words.

These answer "how much of the observed structure is already explained by
n-gram statistics?". A property that a low-order Markov surrogate reproduces is
not evidence of anything deeper.
"""

from __future__ import annotations

import random
from collections import defaultdict

Words = list[list[str]]

WORD_BOUNDARY = " "


def _fit(sequence: list[str], order: int) -> dict[tuple[str, ...], list[str]]:
    """Successor lists keyed by the preceding ``order`` symbols."""
    table: dict[tuple[str, ...], list[str]] = defaultdict(list)
    for index in range(order, len(sequence)):
        table[tuple(sequence[index - order : index])].append(sequence[index])
    return table


def _generate(
    table: dict[tuple[str, ...], list[str]],
    order: int,
    length: int,
    rng: random.Random,
) -> list[str]:
    """Sample ``length`` symbols, backing off when a context is unseen."""
    contexts = sorted(table)
    state = list(rng.choice(contexts))
    output = list(state)
    while len(output) < length:
        context = tuple(state)
        while context and context not in table:
            context = context[1:]
        successors = table.get(context) or table[rng.choice(contexts)]
        symbol = rng.choice(successors)
        output.append(symbol)
        state = (state + [symbol])[-order:] if order else []
    return output[:length]


def _to_words(stream: list[str]) -> Words:
    """Split a unit stream containing boundary symbols back into words."""
    words: Words = []
    current: list[str] = []
    for symbol in stream:
        if symbol == WORD_BOUNDARY:
            if current:
                words.append(current)
                current = []
        else:
            current.append(symbol)
    if current:
        words.append(current)
    return words


def markov_chars(words: Words, order: int, rng: random.Random) -> Words:
    """Order-``order`` surrogate over units, with word boundaries as a symbol.

    Word lengths are therefore generated by the model, not copied.
    """
    stream: list[str] = []
    for word in words:
        stream.extend(word)
        stream.append(WORD_BOUNDARY)
    return _to_words(_generate(_fit(stream, order), order, len(stream), rng))


def markov_words(words: Words, order: int, rng: random.Random) -> Words:
    """Order-``order`` surrogate over word forms; vocabulary preserved exactly."""
    forms = ["".join(word) for word in words]
    units = dict(zip(forms, words, strict=True))
    generated = _generate(_fit(forms, order), order, len(forms), rng)
    return [units[form] for form in generated]
